@startuml
left to right direction
skinparam linetype polyline
hide circle
hide stereotype
allow_mixing
skinparam linetype ortho
<style>
rectangle {LineColor transparent}
</style>
Title Using Permission for Access Control

skinparam class<<MD>> {
 BorderColor DarkSlateGray
 BackgroundColor YellowGreen
 HeaderBackgroundColor DarkOliveGreen
}

skinparam class<<TM>> {
 BorderColor #505090
 BackgroundColor APPLICATION
 HeaderBackgroundColor SkyBlue
}

rectangle {
class "**Request Context**" as RC<<TM>> {
|_ user identity
|_ organization
|_ purposeOfUse
|_ activity (CRUDE)
|_ patient / subject
  |_ consent
|_ data request parameters
  |_ data categories
}
}

rectangle {
  Package "**FHIR:  Rules**" as AR #OrangeRed {
    collections "Permissions" as P #Orange
    collections "Consent" as C #Orange
  }
}

rectangle {
  class "**DataBase**" as Data<<MD>> {
  |_ Metadata
    |_ data sensitivity
    |_ patient / subject
    |_ organization
    |_ author
    |_ encounter
    |_ purposes of Use allowed
    |_ timeframe
  |_ data
  }
}

node "Access Control Implementation" as ACC {
component "Access Decision" as AC
component "Access Enforcement" as AE
}

circle "FHIR Resources" as done

' Connections
RC -l-> AC
Data -d-> AC
P -d-> AC
C -d-> AC
AC -l-> AE : "Permit/Deny\nLimits"
AE -l-> done

@enduml